export { default as CarouselLg } from "./carousel/Carousel-lg"
export { default as ComicsTitle } from "./carousel/ComicsTitle"
export { default as ComicsImages } from "./carousel/ComicsImages"
export { default as ReadComicsButton } from "./carousel/ComicsCardButton"
export { default as ComicsCarousel } from "./carousel/ComicsCarousel"
export { default as ComicsViewer } from "./carousel/ComicsViewer"
export { default as DoubleText } from "./DoubleText"
