import type { NextPage } from "next"
import Head from "next/head"
import { Carousel } from "../components/ui"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Comics Dao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carousel />
    </div>
  )
}

export default Home
