import type { NextPage } from "next"
import Head from "next/head"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Comics Dao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main>
        <h1 className="font-londrina">Welcome to Comics Dao</h1>
      </main> */}
    </div>
  )
}

export default Home
